### ISSUE TITLE
Refactor tests and helpers as of follow up to PR #1085

### ISSUE THREAD

**Issue by saw-jan** [owncloud/owncloud-sdk#1086]
Tasks:
- [x] implement separate config for test users (#1095)
- [x] use httpHelper in webdavHelper and sharingHelper (#1096)
- [x] refactor tests to use users from user config (#1095)
- [ ] use helper functions from `providerStateHelper` for provider state management (#1098, #1099, #1100)
