### ISSUE TITLE
run pact.io provider side tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/owncloud-sdk#644]
all tests have been converted to pact.io see #500 now we want to use the same contracts to test the provider (oc10 & ocis)
for that we need:
- [x] verify consumer side tests #643
- [x] convert the tests to jest - sub task: #645 - POC in #637
- [x] convert tests to use pactV3 - sub task: #646 - POC in #637
- [x] run provider tests with oc10 in drone - sub task: #647 - POC in #662
- [x] adjust pact interactions so that they also pass provider side (oc10) #709
- [x] run provider tests with ocis in drone - sub task: #648 - done in  #740
- [x] adjust pact interactions so that they also pass provider side (ocis) #747
- [x] adjust interaction for interactions unskipped in https://github.com/owncloud/owncloud-sdk/pull/735
